#!/bin/bash

# All except the tex and bib file
rm article.aux
rm article.bbl
rm article.bcf
rm article.blg
rm article.doc
rm article.docx
rm article.log
rm article.md
rm article.out
rm article.pdf
rm article.rtf
rm article.run.xml
rm article.txt
