#!/bin/bash


pdflatex article.tex --shell-escape
bibtex article.aux
pdflatex article.tex --shell-escape
pdflatex article.tex --shell-escape

# Copy to more descriptive name
cp article.pdf article_babette_20180502.pdf
