#!/bin/bash
cd cover_letter_resubmission
./create_cover_letter_resubmission
cd ..

cd response_letter
./create_response_letter
cd ..

pdfunite \
  cover_letter_resubmission/cover_letter_resubmission.pdf \
  response_letter/response_letter.pdf \
  response_letter.pdf

cp response_letter.pdf ~/babette_response_letter_20180507.pdf

