#!/bin/bash

pdflatex article.tex --shell-escape
bibtex article.aux
pdflatex article.tex --shell-escape
pdflatex article.tex --shell-escape
pandoc article.tex -o article.doc
pandoc article.tex -o article.docx