#!/bin/bash

pandoc response_letter.md -o response_letter.pdf

# Specific names and proprietary formats for communication
pandoc response_letter.md -o ~/babette_response_letter_20180507.pdf
pandoc response_letter.md -o ~/babette_response_letter_20180507.docx
